services:
  devcontainer-expose:
    image: chdotworld/dotworld:php81-ubuntu
    container_name: devcontainer-expose
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_WEBSOCKETS_PORT:-6001}:6001'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '${APP_VOLUME}:/workspaces/${APP_NAME}'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - infrastructure
    depends_on:
      - devcontainer-expose_redis
      - devcontainer-expose_mysql
  devcontainer-expose_mysql:
    image: mysql/mysql-server:8.0
    container_name: devcontainer-expose_mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'devcontainer-expose_mysql_data:/var/lib/mysql'
    networks:
      - infrastructure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  devcontainer-expose_redis:
    image: 'redis:alpine'
    container_name: devcontainer-expose_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'devcontainer-expose_redis_data:/data'
    networks:
      - infrastructure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
networks:
  infrastructure:
    driver: bridge

volumes:
  devcontainer-expose_redis_data:
    driver: local
  devcontainer-expose_mysql_data:
    driver: local
